[package]
name = "escargot"
version = "0.1.0"
authors = ["Ed Page <eopage@gmail.com>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
